# Generated by Django 5.0.3 on 2024-03-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x00000271EF15C0E0>', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='otp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
