# Generated by Django 5.0.3 on 2024-03-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_profile_uid_alter_profile_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000001E6BB4900E0>', max_length=200),
        ),
    ]
