# Generated by Django 5.0.3 on 2024-03-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_remove_profile_mobile_remove_profile_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x0000022B810EC0E0>', max_length=200),
        ),
    ]
