# Generated by Django 5.0.3 on 2024-03-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_profile_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000002998EF7C0E0>', max_length=200),
        ),
    ]
