# Generated by Django 5.0.3 on 2024-03-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_profile_mobile_alter_profile_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mobile',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x00000254064CC0E0>', max_length=200),
        ),
    ]
